### ISSUE TITLE
question: does node have to be set at 10+

### ISSUE THREAD

**Issue by iamclaytonray** [walmartlabs/json-to-simple-graphql-schema#1]
Is it possible to downgrade the supported node engine down to LTS or is `10.0.0` a requirement?

**Comment by maxnachlinger** [comment]
Hey @iamclaytonray - it's probably not news that node 8 reaches the [end of its support life on 12/31/2019](https://nodejs.org/en/about/releases/) - so I guess allowing node-8 would give node-8 users 9 months of use. I'll have a look and see if there's anything node 10 specific and downgrade. If you'd rather not wait, you can alway grab a copy and [remove the restriction](https://github.com/walmartlabs/json-to-simple-graphql-schema/blob/master/package.json#L15) yourself and see if it runs.

**Comment by maxnachlinger** [comment]
Please try version `1.0.2`

**Comment by iamclaytonray** [comment]
Cool, thanks!
