### ISSUE TITLE
Arrays does not produce valid Schema

### ISSUE THREAD

**Issue by entrptaher** [walmartlabs/json-to-simple-graphql-schema#11]
Given this following JSON,
```json
{
  "name": "Example.com",
  "data": [
    {
      "Property 1": "Example.com",
      "Property 3": "Something else"
    },
    {
      "Property 2": "Something else"
    },
    {
      "Property 2": "Something else",
      "Property 3": "Something else"
    }
  ]
}
```

This is the output,
```
type Data { Property1: String Property3: String }

type AutogeneratedMainType { name: String data: [Data ] }
```

Property2 is omitted and there is a Property3 instead.

**Comment by maxnachlinger** [comment]
@entrptaher This is by design, we assume each object in an array has the same properties, so we only grab the properties from the first object.  I wonder if the source service could be fixed, it pushes a lot of complexity on to users of that API if they have to handle an array of objects with inconsistent properties.

**Comment by maxnachlinger** [comment]
@dylancwood @ChrisCrewdson - do you think this treatment of arrays is valid? Although IMHO it's a drag to consume an API that returns arrays of objects with inconsistent properties, we still could still support - for example - gathering up all unique properties from objects in that array.

**Comment by entrptaher** [comment]
The example I mentioned above can be resolved with Json type. Instead of Data type, I used scalar Json type with prisma.

On another note, if I have deeply nested JSON data, I might want to have a structure for that as well recursively. 

```json
[
  {
    "id": "some-id-0",
    "name": "A fun object",
    "color": {
      "id": "color-id-1",
      "name": "Test color"
    },
    "subType": {
      "id": "some-id-1",
      "name": "A fun sub-type",
      "color": {
        "id": "color-id-1",
        "name": "Test color",
        "hex": "#ff0000"
      }
    }
  }
]
```

What can I do to help on this matter?

**Comment by maxnachlinger** [comment]
@entrptaher not sure I understand what you're asking above. The JSON you shared seems to convert reasonably well, give it a try here: https://walmartlabs.github.io/json-to-simple-graphql-schema/

**Comment by entrptaher** [comment]
Once you add just a little more data, the result changes and it gives weird results. If we change the nested arrays/objects, the change is even obvious.

```
[
  {
    "name": "A fun object",
    "color": {
      "id": "color-id-1",
      "name": "Test color"
    },
    "subType": {
      "id": "some-id-1",
      "name": "A fun sub-type",
      "color": {
        "id": "color-id-1",
        "name": "Test color",
        "hex": "#ff0000"
      }
    }
  },
  {
    "id": "some-id-0",
    "color": {
      "id": "color-id-1",
      "name": "Test color"
    },
    "subType": {
      "id": "some-id-1",
      "name": "A fun sub-type",
      "color": {
        "id": "color-id-1",
        "name": "Test color",
        "hex": "#ff0000"
      }
    }
  },
  {
    "id": "some-id-0",
    "name": "A fun object",
    "color": {
      "id": "color-id-1"
    },
    "subType": {
      "id": "some-id-1",
      "name": "A fun sub-type"
    }
  }
]
```

Result:
```
type Color { id: String name: String hex: String }

type SubType { id: String name: String color: Color }

type 0 { name: String subType: SubType color: Color }

type 1 { id: String subType: SubType color: Color }

type 2 { id: String
  name: String
  subType: SubType
  color: Color }

type AutogeneratedMainType { 0: 0 1: 1 2: 2 }
```

One thing is, I know how GraphQL wants everyone to act. You must provide a concrete schema every time. But sometimes there are input with a field or two missing in the input json, it happens. 

So, yes, arrays does not produce valid schema, nested arrays/objects are much more invalid.

**Comment by maxnachlinger** [comment]
I don't think I can add much more here. As I mentioned above, this is by design as we assume each object in an array has the same properties. If you want to transform JSON with arrays containing inconsistent properties, this is probably not a library you should use.
