### ISSUE TITLE
Change main type name of result

### ISSUE THREAD

**Issue by andresloal** [walmartlabs/json-to-simple-graphql-schema#17]
Is there a way or are you just considering telling the function how to name the main type instead of AutogeneratedMainType?

Something like:
```
const json = { jsonInput: '{"name": "Test"}' }
const schema = jsonToSchema("useThisMainTypeName", json);
```

**Comment by maxnachlinger** [comment]
Yup, it does what I tell it to, sometimes that's a problem though :) It should be simple enough to specify a name for the main type, would need to be a cmd line arg as well to support piping in Jason. A PR would be welcome.

**Comment by maxnachlinger** [comment]
If you're using this programmatically, this is already in your power,see: https://github.com/walmartlabs/json-to-simple-graphql-schema/blob/master/lib/index.js#L47 - you can just:
```javascript
import { jsonToSchema } from "@walmartlabs/json-to-simple-graphql-schema/lib";

const schema = jsonToSchema({ baseType: "YourTypeHere",  jsonInput: '{"name": "Test"}' });
console.log(schema.value);
```

**Comment by maxnachlinger** [comment]
@andresloal closing this as it seems as if what you need is supported programmatically. If you want to be able to specify the `baseType` as a cmd line arg that would be a simple PR.

**Comment by andresloal** [comment]
Yeah, I read the code and saw that I can indicate the name of the main type, thanks
