### ISSUE TITLE
Adding an option "prefix" for Type object names

### ISSUE THREAD

**Issue by matteoredaelli** [walmartlabs/json-to-simple-graphql-schema#22]
I'd like to append/merge differerent schemas generated by this tool. It would be useful to be able to create all new Type objects with a prefix string in order to not create conflicts with other schemas...

Is it possible to implement it?

Thanks in advance
Matteo

**Comment by maxnachlinger** [comment]
Hey @matteoredaelli, should be easy enough to pass that through as a command line option and into the code which generates the names. Go ahead and open a PR 😃

**Comment by matteoredaelli** [comment]
Done ;-)

https://github.com/walmartlabs/json-to-simple-graphql-schema/pull/23
