### ISSUE TITLE
ability to assign custom data types for named fields

### ISSUE THREAD

**Issue by halfdanrump** [walmartlabs/json-to-simple-graphql-schema#24]
For instance, I'm using this tool to create a graphQL schema for use with AWS Amplify, and I would like to be able to specify all fields named `createdAt` with a custom data type `AWSDateTime`. Something like `--type createdAt AWSDateTime` would be useful.

**Comment by maxnachlinger** [comment]
I think piping the output to `sed` might be simpler. Depends on whether or not you're using this programmatically I guess.
