### ISSUE TITLE
how can i use description for schema

### ISSUE THREAD

**Issue by junhui75165** [walmartlabs/json-to-simple-graphql-schema#32]
![image](https://user-images.githubusercontent.com/3411959/117754437-f0137e00-b24c-11eb-8ca8-b9a371b9316c.png)
i need to add description for this param 
how to set

**Comment by maxnachlinger** [comment]
This silly tool is for creating a graphql schema from some JSON :) If your JSON has an object with a `description` property, you'll likely get a `description` property in your graphql type. Of course it is possible that I've misunderstood your question entirely :)

**Comment by maxnachlinger** [comment]
Closing this for now - reopen if I've misunderstood your question.
