### ISSUE TITLE
some character that are not supported by graphql to be shown as any object

### ISSUE THREAD

**Issue by veeramarni** [walmartlabs/json-to-simple-graphql-schema#9]
When we have the following data, it was not represented correctly.
For example,

```
    "exclude": {
      "**/.hg": true,
      "**/CVS": true,
      "**/.git": true,
      "**/.svn": true,
      "**/.DS_Store": true
    },
```

gets converted to 

Current output
--
```
type  { hg: Boolean
  git: Boolean
  svn: Boolean
  DS_Store: Boolean }

type Exclude { **/:  **/CVS: Boolean }
```

Expected to be AnyObject or JSONObject

**Comment by maxnachlinger** [comment]
Hmm not sure what `AnyObject` or `JSONObject` are, but they are not GraphQL syntax. Could you share what GraphQL syntax output you expected to receive?

**Comment by veeramarni** [comment]
I was expecting the output to be `string` or similar to the output in https://github.com/taion/graphql-type-json.


```
type Exclude: String 

-or -
type Exclude: JSON

--output
"{\"exclude\":{\"**/.hg\":true,\"**/CVS\":true,\"**/.git\":true,\"**/.svn\":true,\"**/.DS_Store\":true}}"
```

**Comment by maxnachlinger** [comment]
The whole point of this library is to turn a JSON doc into a GraphQL schema, so using a 3rd party JSON scalar type wouldn't really align with that goal. It's also worth noting that when parsing input JSON, we'd have no real way to say for a given property's value "ah this type should be a JSON scalar". 

Having said that, I do think there's an issue parsing the JSON input above. I would have expected this input:
```
{
    "exclude": {
      "**/.hg": true,
      "**/CVS": true,
      "**/.git": true,
      "**/.svn": true,
      "**/.DS_Store": true
    }
}
```
to yield this GraphQL schema:
```
type Exclude { 
  hg: Boolean
  CVS: Boolean
  git: Boolean
  svn: Boolean
  DS_Store: Boolean
}
```
You're probably asking "hey what happened to my `*./` characters? Those are actually [not valid characters for GraphQL field names](https://graphql.github.io/graphql-spec/draft/#Name)

**Comment by maxnachlinger** [comment]
The change to handle illegal characters in GraphQL is in version `2.0.0` and has been published to NPM. You can see the change by going to the [Web-ui](https://walmartlabs.github.io/json-to-simple-graphql-schema/) and pasting this on the left side:
```
{
  "exclude": {
    "**/.hg": true,
    "**/CVS": true,
    "**/.git": true,
    "**/.svn": true,
    "**/.DS_Store": true
  }
}
```

**Comment by maxnachlinger** [comment]
@veeramarni Thanks for finding this bug.
